stuff = raw_input('> ')
words = stuff.split()

first_word = ('direction', 'north')
second_word = ('verb', 'go')
third_word = ('direction', 'south')
fourth_word = ('verb', 'kill')
fifth_word = ('direction', 'east')
sixth_word = ('verb', 'eat')
seventh_word = ('stop', 'the')
eigth_word = ('stop', 'in')
ninth_word = ('stop', 'of')
tenth_word = ('noun', 'bear')
eleventh_word = ('noun', 'princess')
twelveth_word = ('number', '1234')
thirteenth_word = ('number', '3')
fourteenth_word = ('number', '91234')
fifteenth_word = ('error', 'ASDFADFASD')
